version: '3'

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./nginx:/etc/nginx/conf.d
    tty: true
    networks:
      - node-network
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - app

  app:
    build: 
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    entrypoint: docker-entrypoint.sh node index.js
    restart: always
    depends_on:
      - db
      
  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge